<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Template.MobileApp</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.AI.Vision.ImageAnalysis" Version="1.0.0" />
    <PackageReference Include="OllamaSharp" Version="5.4.30" />
    <PackageReference Include="SkiaSharp" Version="4.151.2" />
  </ItemGroup>

</Project>
