// <auto-generated />

namespace WorkFont.Resources.Fonts;

static class CustomIcons
{
	public const string Cat = "\ue900";
	public const string Smile1 = "\ue9e1";
	public const string Smile2 = "\ue9e2";
}